services:
  dashboard-tong-apec-global:
    container_name: dashboard-tong-apec-global
    image: dashboard-tong-apec-global
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://api.apecglobal.net

    network_mode: "host"

    env_file:
      - .env

    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
      - GODEBUG=netdns=go

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3018"]
      interval: 30s
      timeout: 5s
      retries: 3